### ISSUE TITLE
code: 'MODULE_NOT_FOUND'

### ISSUE THREAD

**Issue by roughnecks** [Batur123/shoutcastinfo#3]
Hello,

I'm trying to use shoutcastinfo, I have installed it with npm, added to package.json and I'm loading the module with:

`const shoutcastInfo = require('shoutcastinfo');`

Then I just copy pasted the example with streaminfo, but my bot keeps saying that it cannot find the module.

Also, why in your script example you're loading shoutcastinfo in a different way? i.e.

`const shoutcastInfo = require('shoutcastinfo.js');`

Thanks

**Comment by Batur123** [comment]
Could you send the whole error log please

**Comment by roughnecks** [comment]
https://gist.githubusercontent.com/roughnecks/10ff0e29cc1b29d70dbb9346c8529bea/raw/8a428a454baedd6e9420babcb2a41378b6ad34a6/2022-10-22_13-24-48.txt

**Comment by Batur123** [comment]
Try to install package with npm install shoutcastinfo

**Comment by roughnecks** [comment]
I did that already.

npm install shoutcastinfo

up to date, audited 161 packages in 4s

**Comment by Batur123** [comment]
Remove node_modules and package lock json folder, then run npm install only

**Comment by roughnecks** [comment]
```
npm i
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated appdirectory@0.1.0: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for 
details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

added 193 packages, and audited 195 packages in 46s

45 packages are looking for funding
  run `npm fund` for details
```

Still no dice :(

**Comment by roughnecks** [comment]
I'm running this on WSL Debian Stable

**Comment by Batur123** [comment]
Hey, updated package to version 1.0.14. It will work, npm uninstall and install again.

**Comment by Batur123** [comment]
Don't forget to change the version of package to 1.0.14

**Comment by roughnecks** [comment]
Thanks it's working now but I'm getting this when logging "result":

```
[14:00:50] [LOG]   TypeError: Cannot read property '_text' of undefined
    at /mnt/c/Users/roughnecks/Documents/GitHub/ZED/node_modules/shoutcastinfo/shoutcastinfo.js:47:82
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

Probably an error on my side..

**Comment by roughnecks** [comment]
I also tried `console.log(result.CurrentListeners);'
and it returns another error:

```
/mnt/c/Users/roughnecks/Documents/GitHub/ZED/node_modules/shoutcastinfo/shoutcastinfo.js:28
                        typeof result?.SHOUTCASTSERVER[0]?.LISTENERS[0]?.LISTENER == 'undefined' ? "No Listener" : result?.SHOUTCASTSERVER[0]?.LISTENERS[0]?.LISTENER
                                      ^

SyntaxError: Unexpected token '.'
```
